import { register } from "@tokens-studio/sd-transforms";
import StyleDictionary from "style-dictionary";

// Register Token Studio transforms (handles references, math, color modifiers, etc.)
await register(StyleDictionary);

// Custom transform: map Token Studio token names → shadcn CSS var names
// e.g. "light.primary" → "--primary", "light.card-foreground" → "--card-foreground"
StyleDictionary.registerTransform({
  name: "shadcn/name",
  type: "name",
  filter: (token) => {
    // Only transform light/dark semantic tokens, not global primitives
    const set = token.path[0];
    return set === "light" || set === "dark";
  },
  transform: (token) => {
    // Strip the set prefix (light/dark), keep the rest as the CSS var name
    // e.g. ["light", "primary"] → "primary"
    // e.g. ["light", "card-foreground"] → "card-foreground"
    return token.path.slice(1).join("-");
  },
});

// Custom format: generate globals.css with :root (light) and .dark overrides
StyleDictionary.registerFormat({
  name: "shadcn/css",
  format: async ({ dictionary, options }) => {
    const lightTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "light"
    );
    const darkTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "dark"
    );

    const formatToken = (token) => {
      const name = token.path.slice(1).join("-");
      const value = token.$value ?? token.value;
      // Border radius tokens need px suffix if they're plain numbers
      if (token.$type === "borderRadius" || token.type === "borderRadius") {
        const numVal = parseFloat(value);
        if (!isNaN(numVal) && !String(value).includes("px")) {
          return `  --${name}: ${numVal}px;`;
        }
      }
      return `  --${name}: ${value};`;
    };

    const lightVars = lightTokens.map(formatToken).join("\n");
    const darkVars = darkTokens.map(formatToken).join("\n");

    return [
      `/* Generated by Style Dictionary from tokens/tokens.json */`,
      `/* DO NOT EDIT MANUALLY */`,
      ``,
      `@import "tailwindcss";`,
      `@import "tw-animate-css";`,
      ``,
      `@custom-variant dark (&:is(.dark *));`,
      ``,
      `@theme inline {`,
      `  --color-background: var(--background);`,
      `  --color-foreground: var(--foreground);`,
      `  --font-sans: var(--font-geist-sans);`,
      `  --font-mono: var(--font-geist-mono);`,
      `  --color-sidebar-ring: var(--sidebar-ring);`,
      `  --color-sidebar-border: var(--sidebar-border);`,
      `  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);`,
      `  --color-sidebar-accent: var(--sidebar-accent);`,
      `  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);`,
      `  --color-sidebar-primary: var(--sidebar-primary);`,
      `  --color-sidebar-foreground: var(--sidebar-foreground);`,
      `  --color-sidebar: var(--sidebar);`,
      `  --color-chart-5: var(--chart-5);`,
      `  --color-chart-4: var(--chart-4);`,
      `  --color-chart-3: var(--chart-3);`,
      `  --color-chart-2: var(--chart-2);`,
      `  --color-chart-1: var(--chart-1);`,
      `  --color-ring: var(--ring);`,
      `  --color-input: var(--input);`,
      `  --color-border: var(--border);`,
      `  --color-destructive: var(--destructive);`,
      `  --color-accent-foreground: var(--accent-foreground);`,
      `  --color-accent: var(--accent);`,
      `  --color-muted-foreground: var(--muted-foreground);`,
      `  --color-muted: var(--muted);`,
      `  --color-secondary-foreground: var(--secondary-foreground);`,
      `  --color-secondary: var(--secondary);`,
      `  --color-primary-foreground: var(--primary-foreground);`,
      `  --color-primary: var(--primary);`,
      `  --color-popover-foreground: var(--popover-foreground);`,
      `  --color-popover: var(--popover);`,
      `  --color-card-foreground: var(--card-foreground);`,
      `  --color-card: var(--card);`,
      `  --radius-sm: calc(var(--radius) - 4px);`,
      `  --radius-md: calc(var(--radius) - 2px);`,
      `  --radius-lg: var(--radius);`,
      `  --radius-xl: calc(var(--radius) + 4px);`,
      `}`,
      ``,
      `:root {`,
      lightVars,
      `}`,
      ``,
      `.dark {`,
      darkVars,
      `}`,
      ``,
      `@layer base {`,
      `  * {`,
      `    @apply border-border outline-ring/50;`,
      `  }`,
      `  body {`,
      `    @apply bg-background text-foreground;`,
      `  }`,
      `}`,
      ``,
    ].join("\n");
  },
});

// Build
const sd = new StyleDictionary({
  source: ["tokens/tokens.json"],
  preprocessors: ["tokens-studio"],
  platforms: {
    css: {
      transformGroup: "tokens-studio",
      transforms: ["shadcn/name"],
      buildPath: "",
      files: [
        {
          destination: "app/globals.css",
          format: "shadcn/css",
          filter: (token) => {
            // Only output light/dark semantic tokens, not global primitives
            const set = token.path[0];
            return set === "light" || set === "dark";
          },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log("✓ Generated app/globals.css from tokens/tokens.json");
