import { register } from "@tokens-studio/sd-transforms";
import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync } from "fs";

// --- Step 1: Normalize token references ---
// Token Studio sometimes drops the set prefix when editing in the UI.
// e.g. "{colors.blue.600}" instead of "{global.colors.blue.600}"
// Fix these before Style Dictionary processes them.

const raw = readFileSync("tokens/tokens.json", "utf-8");
const tokens = JSON.parse(raw);

// Collect all top-level keys in each set to build a lookup of valid paths
const globalKeys = Object.keys(tokens.global || {});

function normalizeRefs(obj, setName) {
  for (const [key, val] of Object.entries(obj)) {
    if (val && typeof val === "object" && !Array.isArray(val)) {
      if (typeof val.value === "string" && val.value.startsWith("{")) {
        const ref = val.value.slice(1, -1); // strip { }
        // Check if reference is missing its set prefix
        // e.g. "colors.blue.600" should be "global.colors.blue.600"
        const firstPart = ref.split(".")[0];
        if (
          !tokens[firstPart] && // not a valid set name
          globalKeys.includes(firstPart) // but IS a key in global
        ) {
          val.value = `{global.${ref}}`;
        }
      } else {
        normalizeRefs(val, setName);
      }
    }
  }
}

for (const setName of Object.keys(tokens)) {
  normalizeRefs(tokens[setName], setName);
}

// Write normalized tokens to a temp file for Style Dictionary
const normalizedPath = "tokens/.tokens-normalized.json";
writeFileSync(normalizedPath, JSON.stringify(tokens, null, 2));

// --- Step 2: Register Token Studio transforms ---
await register(StyleDictionary);

// --- Step 3: Custom format for shadcn globals.css ---
StyleDictionary.registerFormat({
  name: "shadcn/css",
  format: async ({ dictionary }) => {
    const lightTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "light"
    );
    const darkTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "dark"
    );

    const formatToken = (token) => {
      const name = token.path.slice(1).join("-");
      const value = token.$value ?? token.value;
      // Border radius tokens need px suffix if they're plain numbers
      if (token.$type === "borderRadius" || token.type === "borderRadius") {
        const numVal = parseFloat(value);
        if (!isNaN(numVal) && !String(value).includes("px")) {
          return `  --${name}: ${numVal}px;`;
        }
      }
      return `  --${name}: ${value};`;
    };

    const lightVars = lightTokens.map(formatToken).join("\n");
    const darkVars = darkTokens.map(formatToken).join("\n");

    return [
      `/* Generated by Style Dictionary from tokens/tokens.json */`,
      `/* DO NOT EDIT MANUALLY */`,
      ``,
      `@import "tailwindcss";`,
      `@import "tw-animate-css";`,
      ``,
      `@custom-variant dark (&:is(.dark *));`,
      ``,
      `@theme inline {`,
      `  --color-background: var(--background);`,
      `  --color-foreground: var(--foreground);`,
      `  --font-sans: var(--font-geist-sans);`,
      `  --font-mono: var(--font-geist-mono);`,
      `  --color-sidebar-ring: var(--sidebar-ring);`,
      `  --color-sidebar-border: var(--sidebar-border);`,
      `  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);`,
      `  --color-sidebar-accent: var(--sidebar-accent);`,
      `  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);`,
      `  --color-sidebar-primary: var(--sidebar-primary);`,
      `  --color-sidebar-foreground: var(--sidebar-foreground);`,
      `  --color-sidebar: var(--sidebar);`,
      `  --color-chart-5: var(--chart-5);`,
      `  --color-chart-4: var(--chart-4);`,
      `  --color-chart-3: var(--chart-3);`,
      `  --color-chart-2: var(--chart-2);`,
      `  --color-chart-1: var(--chart-1);`,
      `  --color-ring: var(--ring);`,
      `  --color-input: var(--input);`,
      `  --color-border: var(--border);`,
      `  --color-destructive: var(--destructive);`,
      `  --color-accent-foreground: var(--accent-foreground);`,
      `  --color-accent: var(--accent);`,
      `  --color-muted-foreground: var(--muted-foreground);`,
      `  --color-muted: var(--muted);`,
      `  --color-secondary-foreground: var(--secondary-foreground);`,
      `  --color-secondary: var(--secondary);`,
      `  --color-primary-foreground: var(--primary-foreground);`,
      `  --color-primary: var(--primary);`,
      `  --color-popover-foreground: var(--popover-foreground);`,
      `  --color-popover: var(--popover);`,
      `  --color-card-foreground: var(--card-foreground);`,
      `  --color-card: var(--card);`,
      `  --radius-sm: calc(var(--radius) - 4px);`,
      `  --radius-md: calc(var(--radius) - 2px);`,
      `  --radius-lg: var(--radius);`,
      `  --radius-xl: calc(var(--radius) + 4px);`,
      `}`,
      ``,
      `:root {`,
      lightVars,
      `}`,
      ``,
      `.dark {`,
      darkVars,
      `}`,
      ``,
      `@layer base {`,
      `  * {`,
      `    @apply border-border outline-ring/50;`,
      `  }`,
      `  body {`,
      `    @apply bg-background text-foreground;`,
      `  }`,
      `}`,
      ``,
    ].join("\n");
  },
});

// --- Step 4: Build ---
const sd = new StyleDictionary({
  source: [normalizedPath],
  preprocessors: ["tokens-studio"],
  log: { verbosity: "silent" },
  platforms: {
    css: {
      transformGroup: "tokens-studio",
      buildPath: "",
      files: [
        {
          destination: "app/globals.css",
          format: "shadcn/css",
          filter: (token) => {
            const set = token.path[0];
            return set === "light" || set === "dark";
          },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log("✓ Generated app/globals.css from tokens/tokens.json");
